version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "usersapi"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-64m50g9f96zn"
s3_prefix = "usersapi"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
